services:
  frontend:
    image: web-ui:0.1
    ports:
      - "3000:3000"
    depends_on:
      - backend
  backend:
    image: sitter:0.1
    ports:
      - "8080:8080"
    depends_on:
      - redis
      - db
    environment:
      POSTGRES_USER: ublog
      POSTGRES_PASSWORD: ublog_password
      POSTGRES_DB: blogdb
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      REDIS_ADDR: "redis:6379"
      REDIS_PASSWORD: redis_pw
      REDIS_DB: 0
      JWT_SECRET_KEY: secret_key
      MIGRATE_IN_CODE: true
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: ublog
      POSTGRES_PASSWORD: ublog_password
      POSTGRES_DB: blogdb
    ports:
      - "5432:5432"
    volumes:
      - blog_pg:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - blog_redis:/data

volumes:
  blog_pg:
  blog_redis: